# https://cmake-format.readthedocs.io/en/latest/cmake-lint.html
lint:
  # Disable all the readability checks.
  disabled_codes:
    [
      "R0911",
      "R0912",
      "R0913",
      "R0914",
      "R0915",
      "C0103",
      "C0304",
      "C0111",
      "C0301",
      "C0303",
      "C0305",
      "C0307",
    ]
