repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-yaml
    - id: trailing-whitespace
    - id: end-of-file-fixer

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v14.0.6'
  hooks:
  - id: clang-format
    types_or: [c++, c]

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.10
  hooks:
  - id: cmake-format
  - id: cmake-lint
